### ISSUE TITLE
Information on GPU and Memory

### ISSUE THREAD

**Issue by st164137** [lliuz/ARFlow#25]
Hi,

Could you please let me know which GPU have you used to train the model. When I run the program with some modifications cuda is going out of memory.

**Comment by lliuz** [comment]
I trained it with GTX1080ti / TITAN X On 12/22/2020 00:23, st164137 wrote: 
Hi,
Could you please let me know which GPU have you used to train the model. When I run the program with some modifications cuda is going out of memory.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/lliuz/ARFlow/issues/25",
"url": "https://github.com/lliuz/ARFlow/issues/25",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by st164137** [comment]
Could you please also let me know the training time ?
